name: Upload to Alidrive(Mod)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true      

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Aria2/Uploader
        run: |
          python ./aria2/add_tracker.py
          url=$(curl -fsSL https://api.github.com/repos/aoaostar/alidrive-uploader/releases/latest | grep -Eo 'https.*?linux_amd64.tar.gz')
          curl -L "$url" | tar -xz
          mv alidrive_uploader_linux_amd64/alidrive /usr/local/bin/alidrive && chmod +x /usr/local/bin/alidrive

      - name: Download Video
        run: |
          aria2c --conf-path=./aria2/aria2.conf -d Mod "${{ github.event.inputs.url }}"

      - name: Upload to Alidrive
        env:
          drive_id: ${{ secrets.DRIVE_ID }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
        run: |
          sed -i "s/did/$drive_id/;s/rtoken/$refresh_token/" alidrive.yaml
          videos=("./Mod/${{ github.event.inputs.path }}")
          for video in $videos;do
            echo -n $RANDOM >> "$video"
          done
          alidrive -c alidrive.yaml Mod Remote

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 20
