name: Upload to Alidrive(JAV)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      video:
        description: 'Video File Path(Wildcard support)'
        required: true
      vid:
        description: 'JAV ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Aria2/FFmpeg/Uploader
        run: |
          pip --quiet install bs4 && python ./aria2/add_tracker.py
          wget -q https://github.com/eugeneware/ffmpeg-static/releases/latest/download/ffmpeg-linux-x64 -O /usr/local/bin/ffmpeg
          chmod +x /usr/local/bin/ffmpeg
          url=$(curl -fsSL https://api.github.com/repos/aoaostar/alidrive-uploader/releases/latest | grep -Eo 'https.*?linux_amd64.tar.gz')
          curl -L "$url" | tar -xz
          mv alidrive_uploader_linux_amd64/alidrive /usr/local/bin/alidrive && chmod +x /usr/local/bin/alidrive

      - name: Get JAV info
        run: |
            python javinfo.py ${{ github.event.inputs.vid }}
            mv x86_64-unknown-linux-musl.tar.gz ${{ github.event.inputs.vid }}.jpg

      - name: Download video
        run: | 
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Process video
        run: |
          ffmpeg -hide_banner -i ${{ github.event.inputs.video }} -i ${{ github.event.inputs.vid }}.jpg \
          -map 0 -map 1 -c copy -disposition:v:1 attached_pic ${{ github.event.inputs.vid }}.mp4
          
      - name: Upload to Alidrive
        env:
          drive_id: ${{ secrets.DRIVE_ID }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
        run: |
          sed -i "s/did/$drive_id/;s/rtoken/$refresh_token/" alidrive.yaml
          alidrive -c alidrive.yaml ${{ github.event.inputs.vid }}.jpg Remote/JAV
          alidrive -c alidrive.yaml ${{ github.event.inputs.vid }}.mp4 Remote/JAV
      
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 90
          keep_minimum_runs: 30      
