name: Upload to Alidrive

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true    

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Aria2/Uploader
        run: |
          python ./aria2/add_tracker.py
          curl -sL https://raw.githubusercontent.com/aoaostar/alidrive-uploader/v2/install.sh | bash
          mv alidrive_uploader_linux_amd64/alidrive /usr/local/bin/alidrive && chmod +x /usr/local/bin/alidrive

      - name: Download Video
        run: |
          aria2c --conf-path=./aria2/aria2.conf -d Origin "${{ github.event.inputs.url }}"

      - name: Upload to Alidrive
        env:
          drive_id: ${{ secrets.DRIVE_ID }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
        run: |
          sed -i "s/did/$drive_id/;s/rtoken/$refresh_token/" alidrive.yaml
          alidrive -c alidrive.yaml Origin Remote