name: Upload to Artifact

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download File
        run: |
            python ./aria2/add_tracker.py
            aria2c --conf-path=./aria2/aria2.conf -d DownloadDir "${{ github.event.inputs.url }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: DownloadDir

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 20
