name: Upload to Artifact(M3U8)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'M3U8 URL'
        required: true
      name:
        description: 'File Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download File
        run: |
            wget -q https://github.com/eugeneware/ffmpeg-static/releases/latest/download/ffmpeg-linux-x64 -O /usr/local/bin/ffmpeg
            chmod +x /usr/local/bin/ffmpeg
            url=$(wget -qO- https://api.github.com/repos/nilaoda/N_m3u8DL-RE/releases/latest | grep -Eo 'https.*?linux-x64.*?gz')
            wget -q $url && tar xf *linux-x64*.tar.gz && mv N_m3u8DL-RE*/N_m3u8DL-RE . && chmod +x ./N_m3u8DL-RE            
            ./N_m3u8DL-RE "${{ github.event.inputs.url }}" --save-name ${{ github.event.inputs.name }}
            ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.inputs.name }}"
          path: "${{ github.event.inputs.name }}.mp4"
          compression-level: 0

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 0
          delete_workflow_pattern: Upload to Artifact
          delete_run_by_conclusion_pattern: cancelled, failure
