name: Update DHT

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Aria2
        run: |
          python ./aria2/add_tracker.py
          aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: qBittorrent
        run: |
          python ./qBittorrent/dl_qbee.py && chmod +x qbittorrent-nox
          ./qbittorrent-nox --profile=. -d "${{ github.event.inputs.url }}"
          python ./qBittorrent/stats.py
          rm -rf ./qBittorrent/data/BT_backup/*
          rm -rf ./qBittorrent/data/logs/*
          rm -rf ./qBittorrent/downloads/*          


      - name: Transmission
        run: |
          sudo apt install transmission-cli -y
          echo "net.core.rmem_max = 4194304" | sudo tee -a /etc/sysctl.conf
          echo "net.core.wmem_max = 1048576" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          transmission-cli -g ./transmission -w ./tmp "${{ github.event.inputs.url }}"
          rm -rf ./transmission/torrents/*
          rm -rf ./transmission/resume/*
          rm -rf ./tmp

      - name: Update DHT
        env:
          ACTOR: ${{ github.actor }}
        run: |
          git config --local user.email "${ACTOR}@users.noreply.github.com"
          git config --local user.name "${ACTOR}"
          git add ./aria2/dht.dat ./aria2/dht6.dat
          git add ./transmission/dht.dat
          # git add ./qBittorrent/*
          git commit -m 'update'
          git push -f origin main

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0