name: Upload to Release(ZIP)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          #remove-dotnet: 'true'
          #remove-android: 'true'
          #remove-haskell: 'true'

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download
        run: |
          python ./aria2/add_tracker.py
          aria2c --conf-path=./aria2/aria2.conf -d DowloadDir "${{ github.event.inputs.url }}"

      - name: Zip
        run: |
          zip -0 -s 2000m -rm x86_64-unknown-linux-musl.zip DowloadDir

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.tag }} --title v$(date "+%Y%m%d%H%M%S") x86_64-unknown-linux-musl*
      
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 0
          delete_workflow_pattern: Upload to Release
