name: Upload to Release(Raw-2G limit)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      title:
        description: 'Release Title'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          #remove-dotnet: 'true'
          #remove-android: 'true'
          #remove-haskell: 'true'

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download video
        run: |
            python ./aria2/add_tracker.py
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Upload video
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release create ${{ github.run_id }} --title "${{ github.event.inputs.title }}" ${{ github.event.inputs.path }}
      
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
