name: Stream via TorrServer

on:
  workflow_dispatch:
    # 移除了多余的 input 参数，直接在网页端操作即可

jobs:
  stream:
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2
        
      - name: Setup cloudflared tunnel
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: http://localhost:8090

      - name: Download TorrServer
        run: |
            wget https://github.com/YouROK/TorrServer/releases/latest/download/TorrServer-linux-amd64
            chmod +x TorrServer-linux-amd64
            mkdir -p ./torr_data

      - name: Run TorrServer
        run: |
          echo "======================================================="
          echo "✅ TorrServer 即将启动！"
          echo "🌐 请展开上方 [Setup cloudflared tunnel] 步骤查看你的公网网址！"
          echo "⏹️ 观影结束后，请在网页端设置里点击【关闭服务器】，当前 Action 会自动结束。"
          echo "======================================================="
          
          # 直接在前台运行，阻塞当前 Step。进程结束才会进入下一步。
          ./TorrServer-linux-amd64 -d ./torr_data -p 8090

      - name: Delete workflow runs
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 0
          delete_workflow_pattern: Stream via TorrServer
          # 加入了 success，这样你在网页端正常关闭导致的成功运行也会被清理
          delete_run_by_conclusion_pattern: cancelled, failure, success
